name: Auto Merge to Main

on:
  workflow_run:
    workflows: ["StockWiz CI/CD Pipeline - DEV , TEST Y PROD"]
    types:
      - completed

permissions:
  contents: write

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop using exact commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}     # debe ser develop
          fetch-depth: 0

      - name: Verify branch is develop
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" != "develop" ]]; then
            echo "Workflow no proviene de develop. Abortando merge."
            exit 1
          fi

      - name: Setup Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge develop â†’ main
        run: |
          git fetch origin main
          git checkout main
          git merge ${{ github.event.workflow_run.head_sha }} --no-edit
          git push origin main
