name: CD - Prod

on:
  push:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    environment: prod  
    steps:
      - run: echo "Esperando aprobaci√≥n del environment 'prod' "

  build:
    runs-on: ubuntu-latest
    needs: gate
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up -d
          sleep 20
      - name: Smoke health
        run: |
          set -e
          curl -fsS http://localhost:8000/health
          curl -fsS http://localhost:8001/health
          curl -fsS http://localhost:8002/health
      - if: always()
        run: docker compose down -v
